### ISSUE TITLE
Reduce permissions to this org/repo

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/github-mgmt#9]
In the rush to set this repo up and make bulk changes, extensive permissions were given.  Actions that should be taken:

# Reduce repo specific permissions
We currently have

```yaml
  github-mgmt:
    collaborators:
      admin:
        - andyschwab-admin
        - arajasek
        - galargh
        - jennijuju
        - JesseXie
        - mastrwayne-admin
      push:
        - autonome
        - mroth
        - scotthconner
        - web3risk-admin
```

Lets remove all the direct collaborators.  
We can move these folks to the github-mgmt team:
- andyschwab-admin
- arajasek
- jennijuju
- mastrwayne-admin
since they are already owners per https://github.com/orgs/filecoin-project/people?query=role%3Aowner

I believe the rest can be dropped.

# Remove org ownership
In this event @galargh and I were elevated to org owners.  We should be removed.  With github-mgmt setup and having access there, we should be self-sufficient in helping with future permission needs.
